
[App]
channel_types = ["tendermint_and_eth"]
Env = "dev"
log_level = "debug"

[log]
log_file_name = "teleport-relayer"
logmax_age = 365
logrotation_time = 24

[Chain]

[Chain.Dest]
chain_type = "eth"

[Chain.Dest.Cache]
filename = "destdata"
start_height = 10016108

[Chain.Dest.Eth]
chain_id = 4
chain_name = "test-eth"
gas_limit = 5100000
max_gas_price = 3000000000
tip_coefficient = 0.2
uri = "https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
Update_client_frequency = 2

[Chain.Dest.Eth.Contracts]

[Chain.Dest.Eth.Contracts.Ack_packet]
Addr = "0xF7cb799aeC98F45775114a43b57f80ad95a18aD6"
Opt_priv_key = "6995eddbc393d46b4bad576d1de73f5345782af4d003739176807ac3cbe969f6"
Topic = "AckWritten((uint64,string,string,string,string[],bytes[]),bytes)"

[Chain.Dest.Eth.Contracts.Client]
Addr = "0xbdB5D52C1F8BF7036D593A2A0fE5E6e48415a9fa"
Opt_priv_key = "6995eddbc393d46b4bad576d1de73f5345782af4d003739176807ac3cbe969f6"
Topic = ""

[Chain.Dest.Eth.Contracts.Packet]
Addr = "0xF7cb799aeC98F45775114a43b57f80ad95a18aD6"
Opt_priv_key = "6995eddbc393d46b4bad576d1de73f5345782af4d003739176807ac3cbe969f6"
Topic = "PacketSent((uint64,string,string,string,string[],bytes[]))"


[Chain.Source]
Chain_type = "tendermint"

[Chain.Source.Cache]
Filename = "sourcedata"
start_height = 23647


[Chain.Source.Tendermint]
Chain_id = "teleport_7001-1"
Chain_name = "teleport"
Clean_packet_enabled = true
Gas = 0
grpc_addr = "10.41.20.10:9090"
request_timeout = 100
update_client_frequency = 1

[Chain.Source.Tendermint.Fee]
Amount = 0
Denom = ""

[Chain.Source.Tendermint.Key]
Name = "node0"
Password = "1234567890"
mnemonic = "near unhappy decade march tourist moral away govern zoo patient silk youth burger mix label mercy chat exhibit habit degree gospel banana pear caution"
